# Generated by Django 4.1 on 2023-08-08 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_image_image_id_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='hours_active',
        ),
        migrations.AddField(
            model_name='statistics',
            name='default_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 0, 0)),
        ),
    ]
