# Generated by Django 4.1 on 2023-08-08 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_statistics_hours_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='default_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 0, 0)),
        ),
    ]
