# Generated by Django 4.1 on 2023-08-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_statistics_default_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='default_date',
        ),
    ]
