# Generated by Django 4.1 on 2023-08-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_statistics_default_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user_id',
        ),
    ]
